命令稿啟動於 2018年03月13日 下午 10:18:34
]0;~/lab-1
[32macer@LAPTOP-83E7PRGI [33m~/lab-1[0m
$ whoami;pwd
acer
/home/acer/lab-1
]0;~/lab-1
[32macer@LAPTOP-83E7PRGI [33m~/lab-1[0m
$ git config -l
user.email=a0920919833@gmail.com
user.name=E24066797
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.origin.url=https://github.com/E24066797/lab-1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=README.txt
branch.master.merge=refs/heads/master
remote.lab-1.script.url=https://github.com/E24066797/lab-1
remote.lab-1.script.fetch=+refs/heads/*:refs/remotes/lab-1.script/*
remote.partB.cpp.url=https://github.com/E24066797/lab-1
remote.partB.cpp.fetch=+refs/heads/*:refs/remotes/partB.cpp/*
remote.README.txt.url=https://github.com/E24066797/lab-1
remote.README.txt.fetch=+refs/heads/*:refs/remotes/README.txt/*
remote.partB.script.url=https://github.com/E24066797/lab-1
remote.partB.script.fetch=+refs/heads/*:refs/remotes/partB.script/*
]0;~/lab-1
[32macer@LAPTOP-83E7PRGI [33m~/lab-1[0m
$ git clone https://github.com/E24066797/lab-1.git
fatal: destination path 'lab-1' already exists and is not an empty directory.
]0;~/lab-1
[32macer@LAPTOP-83E7PRGI [33m~/lab-1[0m
$ gir[Kt clone https://github.com/E24066797/lab-1
fatal: destination path 'lab-1' already exists and is not an empty directory.
]0;~/lab-1
[32macer@LAPTOP-83E7PRGI [33m~/lab-1[0m
$ exit

命令稿已於 2018年03月13日 下午 10:19:32
 完成